### ISSUE TITLE
CMD bash fetch_mmdb.bash in docker image

### ISSUE THREAD

**Issue by eoger** [mozilla-services/pairsona#23]
Right now `docker run` gives me:

```
docker run --rm --name pairsona mozilla/pairsona:latest
Sep 18 14:22:51.398 ERRO Cannot find geoip database: mmdb/latest/GeoLite2-City.mmdb
````

**Comment by crella823-dev** [comment]
> Right now `docker run` gives me:
> 
> ```
> docker run --rm --name pairsona mozilla/pairsona:latest
> Sep 18 14:22:51.398 ERRO Cannot find geoip database: mmdb/latest/GeoLite2-City.mmdb
> ````

Need help with this and coding in General. My name is Crystal Rella please look me up, I follow back and I have a lot to learn. I run a non profit organization and could use the help
