### ISSUE TITLE
Provide metadata information for incoming messages.

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/pairsona#8]
It has been requested that the two sides should exchange some elements of metadata along with the crypto block being exchanged. 

The sender format may be JSON and similar to:
```json
{
 "data":"aB12Cx...", 
 "browser":"nightly",
 "os":"Windows 10",
 "device":"desktop"
}
```
This would be extended by the channelserver to include some information based on the incoming IP (e.g. ...
```json
{
  ...
  "remote": {
     "IP": "fe80::e3aa:8e62:4ad5:c3c6",
     "location":"London, UK",
     "browser": "nightly",
     "os": "Windows 10",
   }
}
```
and sent to the receiver.

**Comment by jrconlin** [comment]
I'm kind of ok with the sender providing the info. There are other issues with geoip location information (e.g. VPNs and proxies). We could have the sender sign the data, but then there's the question of what the key material is. For now, let's keep things simple and presume the customer is not the target of a state level attacker.

**Comment by jrconlin** [comment]
rfkelly requested that meta information for both parties be returned. I'm not sure how each party will be identified. ("local" vs. "remote"?)

**Comment by jrconlin** [comment]
Trying to come up with a structure for the data response. Part of the complexity is that we have two sets of data, one coming from the remote, one from the server. We assign a random ID to each connector we could use to differentiate between sides and sources. 

e.g. if a connection joins and gets:
```json
{
  "id": "14933706757974331471",
  "link": "/v1/ws/35205f3eda6040a7b7da2783ded499cb"
}
```
and sends something like:
```json
{
  "data": "Ab12c34e...",
  "meta": {
    "ua": "Mozilla/5.0 (X11; Ubuntu; ...",
     }
 }
```
The server might reply with:
```json
{
  "data": "Ab12c34e...",
  "meta": {
      "14933706757974331471": {
          "ua": "Mozilla/5.0 (X11; Ubuntu; ...",
          "request": {
                "ua": "Mozilla/5.0 (X11; Ubuntu; ...",
                "addr": "192.168.1.0",
                "city": "san jose",
                "region": "california",
                "country": "us",
          }
      },
      "17671119698534399714": {
          "ua": "Mozilla/5.0 (X11; Ubuntu; ...",
          "request": {
                "ua": "Mozilla/5.0 (X11; Ubuntu; ...",
                "addr": "192.168.1.1",
                "city": "san jose",
                "region": "california",
                "country": "us",
          }
      },
   }
}
```

The problem may be that each client needs to be aware of the assigned ID so that it can determine which record it should pay attention to.

@shane-tomlinson Does this look good to you?

**Comment by rfk** [comment]
Are we making trouble for ourselves by having this behave more like a chat room than a pipe?  Within the scope of the pairing process, it doesn't seem useful for a client to receive an echo of its own messages back from the server.

**Comment by jrconlin** [comment]
While based off of a chat server, each channel doesn't see it's own messages, only messages from the other connector. (The server assigns an ID to each connection and then just filters that ID from the broadcast.) If the sender *is* seeing it's own messages echoed back, then that's a bug.

As for the metadata having multiple elements, that was suggested by @rfk. He noted that having information for both sides would be useful to ensure against unexpected MITM or other attack. I'm fine with just including the counterpart data (although I'm a bit shy about identifying the data as "sender" since that implies function that may not always be true).

**Comment by rfk** [comment]
> each channel doesn't see it's own messages, only messages from the other connector.
> If the sender is seeing it's own messages echoed back, then that's a bug.

OK great, thanks.  I don't have any reason to believe this is hppening, I must have just misunderstood what you were getting at with the clients needing to be aware of their own ids.

> I'm fine with just including the counterpart data

I am also fine with this in the interests of YAGNI.
